{% set name = "imod" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebc893f4d6a472db12f64be68d7da2a08bf55d0cf5d8053cdbf6b2ea2e891a8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - affine
    - bottleneck
    - cftime >=1.0
    - contextily >=1.0
    - cytoolz
    - dask
    - geopandas
    - graphviz
    - jinja2
    - matplotlib-base
    - netcdf4
    - numba >=0.50
    - numpy
    - pandas
    - pooch
    - pygeos
    - python-dateutil
    - python-graphviz
    - pyvista
    - rasterio >=1.0
    - scipy
    - scooby
    - shapely >=1.8
    - tomli >=1.1.0
    - tomli-w
    - toolz
    - tqdm
    - vtk >=9.0
    - xarray >=0.15
    - xugrid >=0.1.6
    - zarr

test:
  imports:
    - imod

about:
  home: https://gitlab.com/deltares/imod/imod-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Work with iMOD MODFLOW models

  description: |
    The imod Python package is an open source project to make working with
    MODFLOW groundwater models in Python easier. It builds on top of popular
    packages such as xarray, pandas, geopandas, dask,  and rasterio to provide
    a versatile toolset for working with (large) groundwater (modeling) data.
  doc_url: https://deltares.gitlab.io/imod/imod-python/
  dev_url: https://gitlab.com/deltares/imod/imod-python

extra:
  recipe-maintainers:
    - luitjansl
    - JoerivanEngelen
    - visr
    - Huite
